#!/bin/sh

# Add archtectures
dpkg --add-architecture arm64
dpkg --add-architecture armhf

# Install GnuPG and cURL
apt -y update
apt -y install gnupg curl

# Add GPG key
curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3874da771b351757' | gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/atmark-debian.gpg

# Setup debian repos
cat << EOF > /etc/apt/preferences.d/atmark-techno-pin-1001
Package: *
Pin: origin download.atmark-techno.com
Pin-Priority: 1001
EOF

cat << EOF > /etc/apt/sources.list
deb http://ftp.jp.debian.org/debian/ bookworm main non-free-firmware
deb-src http://ftp.jp.debian.org/debian/ bookworm main non-free-firmware
deb http://security.debian.org/debian-security bookworm-security main non-free-firmware
deb-src http://security.debian.org/debian-security bookworm-security main non-free-firmware
deb http://ftp.jp.debian.org/debian/ bookworm-updates main non-free-firmware
deb-src http://ftp.jp.debian.org/debian/ bookworm-updates main non-free-firmware
EOF

cat << EOF > /etc/apt/sources.list.d/atmark-techno.list
deb https://download.atmark-techno.com/debian/ bookworm main contrib non-free-firmware
deb-src https://download.atmark-techno.com/debian/ bookworm main contrib
EOF

# Install packages
apt -y update
apt -y install x1-essential wireless-regdb vim git
